project:
  type: website
  output-dir: docs

website:
  title: "Ryan Green"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - resources.qmd

format:
  html:
    theme: 
      light: Yeti
      dark: Vapor
    css: styles.css
    toc: true

editor: visual

