project:
  type: website
  output-dir: docs

website:
  title: "Ryan Green"
  navbar:
    left:
      - href: "https://drive.google.com/file/d/1SPH953WcCA4TST3ZHSwXDtfryY5FHvk6/view?usp=sharing"
        text: Resume
      - href: posts.qmd
        text: Projects
  page-footer: 
    background: light
    left: Copyright 2026, Ryan Green
    right: Built with GitHub

format:
  html:
    theme:
      light: styles.scss
      dark: styles-dark.scss
    mainfont: Lora
    include-in-header: anti-flash.html

editor: visual

