project:
  type: website
  output-dir: docs

website:
  title: "Ryan Green"
  navbar:
    left:
      - href: index.qmd
        text: Home
#      - href: about.qmd
#      - href: resources.qmd
      - href: "https://drive.google.com/file/d/1pPYsrOMEOLsAciXQtTcaQqJ9qIYZRQOS/view?usp=sharing" 
        text: Resume
      - href: posts.qmd
        text: Blog
  page-footer: 
    background: light
    left: Copyright 2024, Ryan Green
    right: Built with GitHub

format:
  html:
    theme: styles.scss
    mainfont: Lora
    toc: true

editor: visual

