project:
  type: website
  output-dir: docs

website:
  title: "Ryan Green"
  navbar:
    left:
      - href: "https://drive.google.com/file/d/1MS_C8J8KsRtBbLfbkYMSX2ybvAS443KZ/view?usp=sharing"
        text: Resume
      - href: posts.qmd
        text: Blog
  page-footer: 
    background: light
    left: Copyright 2024, Ryan Green
    right: Built with GitHub

format:
  html:
    theme: styles.scss
    mainfont: Lora

editor: visual

